name = "foot"
description = "Create platform motor control"

[pilot]
display_name = "Foot"
description = "Drive base interface for the iRobot Create"

[[pilot.topics]]
name = "/odom"
type = "nav_msgs/msg/Odometry"
access = "ro"
presentation = "pose"
qos = { history = "keep_last", depth = 10, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/joint_states"
type = "sensor_msgs/msg/JointState"
access = "ro"
presentation = "status"
qos = { history = "keep_last", depth = 10, reliability = "reliable", durability = "volatile" }

[[actions]]
type = "git_clone"
repo = "https://github.com/autonomylab/create_robot.git"
dest = "create_robot"

[[actions]]
type = "git_clone"
repo = "https://github.com/revyos-ros/libcreate.git"
dest = "libcreate"
branch = "fix-std-string"

[systemd]
description = "Psyched Foot Motion"
after = ["network.target"]
restart = "on-failure"
restart_sec = 4
launch_command = """
set -euo pipefail
exec ros2 launch create_bringup create_1.launch
"""
shutdown_command = """
set -euo pipefail
PATTERN="ros2 launch create_bringup create_1.launch"
TIMEOUT=${TIMEOUT:-10}
if ! pgrep -f "$PATTERN" >/dev/null 2>&1; then
  echo "[foot/shutdown] No matching processes found for pattern: $PATTERN"
  exit 0
fi

echo "[foot/shutdown] Sending SIGTERM to processes for: $PATTERN"
pkill -TERM -f "$PATTERN" || true

for ((i=0; i<TIMEOUT; i++)); do
  sleep 1
  if ! pgrep -f "$PATTERN" >/dev/null 2>&1; then
    echo "[foot/shutdown] All processes stopped"
    exit 0
  fi
done

echo "[foot/shutdown] Forcing SIGKILL for remaining processes"
pkill -KILL -f "$PATTERN" || true
"""
