[unit.foot]
# TODO: Replace hardcoded 'kilted' prefix with ${ROS_DISTRO} once substitution is available
apt = ["libboost-all-dev", "ros-kilted-diagnostic-updater", "ros-kilted-xacro"]
pip = []
patches = ["modules/foot/apply_patches.sh"]
launch = "modules/foot/launch_unit.sh"
shutdown = "modules/foot/shutdown_unit.sh"
pilot_control = "modules/foot/pilot/index.html"

[[unit.foot.git]]
url = "https://github.com/autonomylab/create_robot.git"

[[unit.foot.git]]
url = "https://github.com/revyos-ros/libcreate.git"
branch = "fix-std-string"
path = "libcreate"

[unit.foot.ros]
workspace = "."

[pilot]
display_name = "Foot"
description = "Drive base interface for the iRobot Create"
regimes = ["mobility"]
