name = "foot"
description = "Create platform motor control"

[pilot]
display_name = "Foot"
description = "Drive base interface for the iRobot Create"
regimes = ["mobility"]

[[pilot.topics]]
name = "/odom"
type = "nav_msgs/msg/Odometry"
access = "ro"
presentation = "pose"
qos = { history = "keep_last", depth = 10, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/joint_states"
type = "sensor_msgs/msg/JointState"
access = "ro"
presentation = "status"
qos = { history = "keep_last", depth = 10, reliability = "reliable", durability = "volatile" }

[[actions]]
type = "git_clone"
repo = "https://github.com/autonomylab/create_robot.git"
dest = "create_robot"

[[actions]]
type = "git_clone"
repo = "https://github.com/revyos-ros/libcreate.git"
dest = "libcreate"
branch = "fix-std-string"

[[actions]]
type = "apt_install"
# TODO: Introduce variable substitution for ROS distro in module.toml files and replace 'kilted' with '${ROS_DISTRO}'
packages = [
    "libboost-all-dev",
    "ros-kilted-diagnostic-updater",
    "ros-kilted-xacro",
]
update = true

[systemd]
description = "Psyched Foot Motion"
after = ["network.target"]
restart = "on-failure"
restart_sec = 4
launch_command = "${MODULE_DIR}/foot.launch.sh"
shutdown_command = "${MODULE_DIR}/foot.shutdown.sh"
