[package]
name = "psh"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
hostname = "0.3"
which = "6"
duct = "0.13"
anyhow = "1"
