[unit.nav]
apt = [
    "python3-opencv",
    "python3-numpy",
]
pip = [
    "opencv-python",
    "numpy",
]
patches = [
    "modules/nav/scripts/install_nav2_deps.sh",
    "modules/nav/scripts/link_nav2_sources.sh",
    "modules/nav/scripts/build_psyched_nav.sh",
]
launch = "modules/nav/launch_unit.sh"
shutdown = "modules/nav/shutdown_unit.sh"
pilot_control = "modules/nav/pilot/components/NavModulePanel.tsx"

[unit.nav.ros]
workspace = "."
packages = ["psyched_nav"]

[pilot]
display_name = "Nav"
description = "Autonomous navigation stack"
regimes = ["navigation"]

[[pilot.topics]]
name = "/map"
type = "nav_msgs/msg/OccupancyGrid"
access = "ro"
presentation = "map"
qos = { history = "keep_last", depth = 1, reliability = "reliable", durability = "transient_local" }

[[pilot.topics]]
name = "/plan"
type = "nav_msgs/msg/Path"
access = "ro"
presentation = "path"
qos = { history = "keep_last", depth = 5, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/amcl_pose"
type = "geometry_msgs/msg/PoseWithCovarianceStamped"
access = "ro"
presentation = "pose"
qos = { history = "keep_last", depth = 5, reliability = "reliable", durability = "volatile" }
