name = "nav"
description = "Navigation stack bring-up"

[pilot]
display_name = "Nav"
description = "Autonomous navigation stack"
regimes = ["navigation"]

[[pilot.topics]]
name = "/map"
type = "nav_msgs/msg/OccupancyGrid"
access = "ro"
presentation = "map"
qos = { history = "keep_last", depth = 1, reliability = "reliable", durability = "transient_local" }

[[pilot.topics]]
name = "/plan"
type = "nav_msgs/msg/Path"
access = "ro"
presentation = "path"
qos = { history = "keep_last", depth = 5, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/amcl_pose"
type = "geometry_msgs/msg/PoseWithCovarianceStamped"
access = "ro"
presentation = "pose"
qos = { history = "keep_last", depth = 5, reliability = "reliable", durability = "volatile" }

[[actions]]
type = "link_packages"
packages = ["psyched_nav"]

[[actions]]
type = "run"
description = "Install Nav2 apt dependencies when available"
script = "scripts/install_nav2_deps.sh"
optional = true

[[actions]]
type = "run"
description = "Link custom Nav2 sources when NAV2_LOCAL_DIR is set"
script = "scripts/link_nav2_sources.sh"
optional = true

[[actions]]
type = "run"
description = "Optionally build psyched_nav"
script = "scripts/build_psyched_nav.sh"
optional = true

[systemd]
description = "Psyched Navigation"
after = ["network-online.target"]
wants = ["network-online.target"]
restart = "on-failure"
restart_sec = 5
launch_command = "${MODULE_DIR}/nav.launch.sh"
shutdown_command = "${MODULE_DIR}/nav.shutdown.sh"
