[unit.viscera]
apt = []
pip = []
launch = "modules/viscera/launch_unit.sh"
shutdown = "modules/viscera/shutdown_unit.sh"
pilot_control = "modules/viscera/pilot/components/VisceraModulePanel.tsx"

[unit.viscera.ros]
workspace = "."
packages = ["viscera"]
