[unit.viscera]
apt = []
pip = []
launch = "modules/viscera/launch_unit.sh"
shutdown = "modules/viscera/shutdown_unit.sh"
pilot_control = "modules/viscera/pilot/components/VisceraModulePanel.tsx"

[unit.viscera.ros]
workspace = "."
packages = ["viscera"]

[pilot]
display_name = "Viscera"
description = "System telemetry and host health monitoring"
regimes = ["system"]

[[pilot.topics]]
name = "host/health"
type = "psyched_msgs/msg/HostHealth"
access = "ro"
presentation = "diagnostics"
