name = "imu"
description = "MPU6050 inertial measurement integration"

[pilot]
display_name = "IMU"
description = "Inertial measurement data from the MPU6050"
regimes = ["perception"]

[[pilot.topics]]
name = "/imu/data"
type = "sensor_msgs/msg/Imu"
access = "ro"
presentation = "imu"
qos = { history = "keep_last", depth = 20, reliability = "reliable", durability = "volatile" }

[[actions]]
type = "git_clone"
repo = "https://github.com/hiwad-aziz/ros2_mpu6050_driver.git"
dest = "ros2_mpu6050_driver"

[[actions]]
type = "run"
description = "Ensure mpu6050 header includes <array>"
script = "scripts/patch_header.sh"
optional = true

[[actions]]
type = "run"
description = "Change the topic name to /imu/data_raw"
script = "scripts/patch_topic.sh"
optional = true

[[actions]]
type = "apt_install"
packages = ["libi2c-dev", "i2c-tools", "ros-kilted-imu-filter-madgwick"]
update = false

[systemd]
description = "Psyched IMU Sensor"
after = ["network.target"]
restart = "on-failure"
restart_sec = 4
launch_command = "${MODULE_DIR}/imu.launch.sh"
shutdown_command = "${MODULE_DIR}/imu.shutdown.sh"
