name = "rtabmap"
description = "RTAB-Map placeholder"

[[actions]]
type = "run"
description = "Inform user about manual RTAB-Map installation"
command = """
echo "RTAB-Map setup requires manual installation on supported hosts."
"""
optional = true

[systemd]
description = "Psyched RTAB-Map"
after = ["network-online.target"]
wants = ["network-online.target"]
restart = "on-failure"
restart_sec = 10
launch_command = """
set -euo pipefail
echo "RTAB-Map launch stub"
echo "RTAB-Map is not supported in this environment. Configure mapping on a host with RTAB-Map available or use a different SLAM node."
exit 0
"""
shutdown_command = """
set -euo pipefail
echo "[rtabmap] No shutdown actions defined."
"""
