name = "will"
description = "Behaviour tree orchestrator"

[pilot]
display_name = "Will"
description = "Behaviour tree coordinator"
regimes = ["behavior"]

[[pilot.topics]]
name = "/psyched/will/status"
type = "std_msgs/msg/String"
access = "ro"
presentation = "status"
qos = { history = "keep_last", depth = 5, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/psyched/will/blackboard"
type = "std_msgs/msg/String"
access = "ro"
presentation = "log"
qos = { history = "keep_last", depth = 20, reliability = "reliable", durability = "volatile" }

[[actions]]
type = "link_packages"
packages = ["psyched_bt"]

[[actions]]
type = "apt_install"
packages = ["python3-pip", "git"]
update = true

[[actions]]
type = "pip_install"
packages = ["py_trees"]
import_check = ["py_trees"]
break_system = true

[[actions]]
type = "run"
description = "Install py_trees_ros with Git fallback"
script = "scripts/install_py_trees_ros.sh"
optional = true

[systemd]
description = "Psyched Behaviour Tree"
after = ["network.target"]
restart = "on-failure"
restart_sec = 5
launch_command = "${MODULE_DIR}/will.launch.sh"
shutdown_command = "${MODULE_DIR}/will.shutdown.sh"
