# Nav2 parameters tuned for a small differential-drive robot (Create 1)
# Adjust planners, controller, and footprint according to your testing.
amcl:
  ros__parameters:
    use_map_topic: false
    scan: /scan

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]

  FollowPath:
    plugin: "dwb_core::DWBLocalPlanner"
    # DWB parameters (tune for your robot)
    acc_lim_x: 2.5
    acc_lim_y: 0.0
    acc_lim_theta: 3.2
    max_vel_x: 0.46
    min_vel_x: 0.0
    max_vel_theta: 1.0
    min_vel_theta: -1.0

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0

global_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    footprint:
      - [0.18, 0.18]
      - [0.18, -0.18]
      - [-0.18, -0.18]
      - [-0.18, 0.18]
    resolution: 0.05

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    resolution: 0.05

# Robot footprint: Create 1 approximate 0.36m x 0.36m square; adjust as needed.

