name = "wifi"
description = "User-space Wi-Fi tooling and ROS 2 status publisher"

[pilot]
display_name = "Wi-Fi"
description = "Wireless network health"

[[pilot.topics]]
name = "/wifi_status"
type = "std_msgs/msg/String"
access = "ro"
presentation = "status"
qos = { history = "keep_last", depth = 5, reliability = "reliable", durability = "volatile" }

[[actions]]
type = "link_packages"
packages = ["wifi"]

[[actions]]
type = "ros_run"
package = "wifi"
executable = "wifi_setup"
description = "Prime Wi-Fi status publisher"
optional = true

[systemd]
description = "Psyched Wi-Fi Access Point"
after = ["network.target", "network-online.target"]
wants = ["network-online.target"]
restart = "on-failure"
restart_sec = 3
launch_command = """
set -euo pipefail
IFACE=${IFACE:-wlan0}
AP_IP=${AP_IP:-192.168.50.1}
HOSTNAME=$(hostname)

sudo ip link set "$IFACE" down || true
sudo ip addr flush dev "$IFACE" || true
sudo ip addr add "$AP_IP/24" dev "$IFACE"
sudo ip link set "$IFACE" up

sudo cp dnsmasq.conf /etc/dnsmasq.conf
sudo bash -c "echo 'address=/$HOSTNAME.local/$AP_IP' >> /etc/dnsmasq.conf"

sudo cp avahi-daemon.conf /etc/avahi/avahi-daemon.conf
sudo sed -i "s/^#*host-name=.*/host-name=$HOSTNAME/" /etc/avahi/avahi-daemon.conf

sudo hostapd /etc/hostapd/hostapd.conf &
sudo dnsmasq -C /etc/dnsmasq.conf &
sudo avahi-daemon --no-chroot -f /etc/avahi/avahi-daemon.conf &
(cd www && python3 -m http.server 80) &
wait -n
"""
shutdown_command = """
set -euo pipefail
sudo pkill hostapd || true
sudo pkill dnsmasq || true
sudo pkill avahi-daemon || true
sudo pkill -f 'python3 -m http.server' || true
echo "[shutdown_wifi] Stopped Wi-Fi AP services."
"""
