name = "wifi"
description = "Managed Wi-Fi access point with DHCP, mDNS, and optional internet sharing"

[pilot]
display_name = "Wi-Fi"
description = "Wireless network health"
regimes = ["system"]

[[pilot.topics]]
name = "/wifi_status"
type = "std_msgs/msg/String"
access = "ro"
presentation = "status"
qos = { history = "keep_last", depth = 5, reliability = "reliable", durability = "volatile" }

[[actions]]
type = "link_packages"
packages = ["wifi"]

[[actions]]
type = "pip_install"
packages = ["zeroconf"]
import_check = ["zeroconf"]
break_system = true

[[actions]]
type = "apt_install"
packages = ["hostapd", "dnsmasq", "iproute2", "iw", "iptables"]
update = false

[systemd]
description = "Psyched Wi-Fi Access Point"
after = ["network.target", "network-online.target"]
wants = ["network-online.target"]
restart = "on-failure"
restart_sec = 3
launch_command = "${MODULE_DIR}/wifi.launch.sh"
shutdown_command = "${MODULE_DIR}/wifi.shutdown.sh"
