name = "wifi"
description = "User-space Wi-Fi tooling and ROS 2 status publisher"

[[actions]]
type = "link_packages"
packages = ["wifi"]

[[actions]]
type = "ros_run"
package = "wifi"
executable = "wifi_setup"
description = "Prime Wi-Fi status publisher"
optional = true

[systemd]
description = "Psyched Wi-Fi Access Point"
after = ["network.target", "network-online.target"]
wants = ["network-online.target"]
launch = "modules/wifi/launch.sh"
shutdown = "modules/wifi/shutdown.sh"
restart = "on-failure"
restart_sec = 3
