# Host description for cerebellum
# Controls which modules are enabled and optional installers.

# Install ROS2 on this host during `psh provision`?
setup_ros2 = true

# Install Docker on this host during `psh provision`?
setup_docker = true

# Download speech-stack assets (models, etc.) on this host?
setup_speech = true

# Ordered list of modules to enable for this host. Each entry corresponds to
# a directory under modules/ and its module.toml actions will be executed in
# the same order.
modules = ["foot", "imu", "pilot", "voice", "ear", "eye", "chat"]

# Module configuration now lives under hosts/cerebellum/config/*.toml
# TODO: We need to move these all back to right here. The config should live here in the one host file. There shouldn't be a whole folder underneath this.
