# Pete Rizzlington host config: forebrain
# Heavyweight compute node for LLMs, ASR, TTS.
# Onboard headless laptop with GPU (no screen).

[host]
name = "forebrain"

[provision]
# Bootstrap scripts to run on this host
scripts = [
    "tools/bootstrap/install_deno.sh",
    "tools/bootstrap/install_docker.sh",
    "tools/bootstrap/install_cuda.sh",
]

[features]
docker = true
ros2 = false
cuda = true

[[services]]
name = "tts"
setup = true
up = true

[[services]]
name = "llm"
setup = false
up = true

[[services]]
name = "graphs"
setup = false
up = true

[[services]]
name = "vectors"
setup = false
up = true

[[services]]
name = "asr"
setup = true
up = true
