# Pete Rizzlington host config: forebrain
# Heavyweight compute node for LLMs, ASR, TTS.
# Onboard headless laptop with GPU (no screen).

[host]
name = "forebrain"

[provision]
# Declarative installers executed by psh
installers = ["docker", "cuda"]

[features]
docker = true
ros2 = false
cuda = true

[[services]]
name = "tts"
setup = true
up = true

[[services]]
name = "llm"
setup = false
up = true

[[services]]
name = "graphs"
setup = false
up = true

[[services]]
name = "vectors"
setup = false
up = true

[[services]]
name = "asr"
setup = true
up = true
