# Pete Rizzlington host config: motherbrain
# Midbrain control layer that runs ROS 2 nodes.
# Onboard rpi5

[host]
name = "motherbrain"
roles = ["midbrain", "ros2-control"]

[provision]
# Declarative installers executed by psh
installers = ["ros2"]

[modules.pilot]

  [modules.pilot.env]
  ROS_DOMAIN_ID = "25"

[modules.imu]

  [modules.imu.env]
  ROS_DOMAIN_ID = "25"

[modules.foot]

  [modules.foot.env]
  ROS_DOMAIN_ID = "25"

[modules.eye]

  [modules.eye.env]
  ROS_DOMAIN_ID = "25"

[modules.ear]

  [modules.ear.env]
  ROS_DOMAIN_ID = "25"
  EAR_BACKEND = "service"
  EAR_SERVICE_URI = "ws://forebrain.local:5003/asr"

  [[modules.ear.dependencies]]
  service = "forebrain.asr"
  port = "ws"
  via = "ws://forebrain.local:5003/asr"
  bind_env = "EAR_SERVICE_URI"
  summary = "Consumes Whisper websocket for speech recognition"

[modules.faces]

  [modules.faces.launch]
  [modules.faces.env]
  ROS_DOMAIN_ID = "25"

  [modules.faces.launch.arguments]
  camera_topic = "/camera/color/image_raw"
  faces_topic = "/vision/faces"
  face_detected_topic = "/vision/face_detected"

[modules.gps]

  [modules.gps.launch]
  [modules.gps.env]
  ROS_DOMAIN_ID = "25"

  [modules.gps.launch.arguments]
  frame_id = "gps_link"

[modules.nav]

  [modules.nav.launch]
  [modules.nav.env]
  ROS_DOMAIN_ID = "25"

  [modules.nav.launch.arguments]
  kinect_rgb_topic = "/camera/color/image_raw"
  kinect_depth_topic = "/camera/depth/image_rect_raw"
  camera_frame = "camera_link"

[modules.wifi]

  [modules.wifi.env]
  WIFI_INTERFACE = "wlan0"
  WIFI_CHANNEL = "11"
  WIFI_COUNTRY_CODE = "US"
  WIFI_SSID = "Pete-Net"
  WIFI_ENABLE_NAT = "true"
  WIFI_UPLINK_INTERFACE = "eth0"

[modules.will]

  [modules.will.env]
  ROS_DOMAIN_ID = "25"
  WILL_DEFAULT_REGIME = "idle"

[modules.voice]

  [modules.voice.env]
  ROS_DOMAIN_ID = "25"
  VOICE_BACKEND = "websocket"
  VOICE_TTS_URL = "ws://forebrain.local:5002/tts"

  [[modules.voice.dependencies]]
  service = "forebrain.tts"
  port = "ws"
  via = "ws://forebrain.local:5002/tts"
  bind_env = "VOICE_TTS_URL"
  summary = "Streams synthesized speech from the forebrain TTS service"

[modules.viscera]

  [modules.viscera.env]
  ROS_DOMAIN_ID = "25"
