# Pete Rizzlington host config: motherbrain
# Midbrain control layer that runs ROS 2 nodes.
# Onboard rpi5

[host]
name = "motherbrain"

[provision]
# Declarative installers executed by psh
installers = ["ros2"]

[features]
docker = true
ros2 = true
cuda = false

[[modules]]
name = "pilot"
launch = false
env = { ROS_DOMAIN_ID = "25" }

[[modules]]
name = "imu"
launch = true
env = { ROS_DOMAIN_ID = "25" }

[[modules]]
name = "foot"
launch = true
env = { ROS_DOMAIN_ID = "25" }
