# Pete Rizzlington host config: motherbrain
# Midbrain control layer that runs ROS 2 nodes.
# Onboard rpi5

[host]
name = "motherbrain"

[provision]
# Bootstrap scripts to run on this host
scripts = ["tools/bootstrap/install_ros2.sh"]

[features]
docker = true
ros2 = true
cuda = false
