[unit.ear]
apt = [
    "python3-websockets",
    "python3-numpy",
]
pip = []
launch = "modules/ear/launch_unit.sh"
shutdown = "modules/ear/shutdown_unit.sh"
pilot_control = "modules/ear/pilot/components/EarModulePanel.tsx"

[unit.ear.ros]
workspace = "."
packages = ["ear"]

[pilot]
display_name = "Ear"
description = "Audio intake and VAD telemetry"
regimes = ["audio"]
