name = "ear"
description = "Microphone capture and voice activity detection"

[pilot]
display_name = "Ear"
description = "Audio intake and VAD telemetry"
regimes = ["audio"]

[[pilot.topics]]
name = "/audio/raw"
type = "std_msgs/msg/ByteMultiArray"
access = "ro"
presentation = "oscilloscope"
qos = { history = "keep_last", depth = 5, reliability = "best_effort", durability = "volatile" }

[[pilot.topics]]
name = "/audio/autophony_duration"
type = "std_msgs/msg/UInt32"
access = "ro"
presentation = "gauge"
qos = { history = "keep_last", depth = 10, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/audio/speech_duration"
type = "std_msgs/msg/UInt32"
access = "ro"
# presentation = "diode"
presentation = "gauge"
qos = { history = "keep_last", depth = 10, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/audio/silence_ms"
type = "std_msgs/msg/UInt32"
access = "ro"
presentation = "gauge"
qos = { history = "keep_last", depth = 10, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/audio/speech_segment"
type = "std_msgs/msg/ByteMultiArray"
access = "ro"
presentation = "waveform"
qos = { history = "keep_last", depth = 5, reliability = "best_effort", durability = "volatile" }

[[pilot.topics]]
name = "/audio/transcription"
type = "psyched_msgs/msg/Transcript"
access = "ro"
presentation = "transcription"
qos = { history = "keep_last", depth = 5, reliability = "best_effort", durability = "volatile" }

[[actions]]
type = "link_packages"
packages = ["ear", "psyched_msgs"]


[[actions]]
type = "pip_install"
packages = ["webrtcvad"]
import_check = ["webrtcvad"]
break_system = true

[[actions]]
type = "pip_install"
packages = ["numpy", "faster-whisper"]
import_check = ["numpy", "faster_whisper"]
break_system = true

[[actions]]
type = "apt_install"
packages = [
    "alsa-utils",
    "libasound2-dev",
    "portaudio19-dev",
    "python3-pyaudio",
]
update = true

[systemd]
description = "Psyched Ear Audio Capture"
after = ["network.target"]
restart = "on-failure"
restart_sec = 5
launch_command = "${MODULE_DIR}/ear.launch.sh"
shutdown_command = "${MODULE_DIR}/ear.shutdown.sh"
