name = "ear"
description = "Microphone capture and voice activity detection"

[[actions]]
type = "link_packages"
packages = ["ear", "psyched_msgs"]

[[actions]]
type = "pip_install"
packages = ["pyaudio"]
import_check = ["pyaudio"]
break_system = true

[[actions]]
type = "pip_install"
packages = ["webrtcvad"]
import_check = ["webrtcvad"]
break_system = true

[[actions]]
type = "apt_install"
packages = ["alsa-utils"]
update = true

[systemd]
description = "Psyched Ear Audio Capture"
after = ["network.target"]
launch = "modules/ear/launch.sh"
shutdown = "modules/ear/shutdown.sh"
restart = "on-failure"
restart_sec = 5
