[unit.ear]
apt = ["python3-websockets", "python3-numpy", "alsa-utils"]
pip = ["webrtcvad"]
launch = "modules/ear/launch_unit.sh"
shutdown = "modules/ear/shutdown_unit.sh"
cockpit_control = "modules/ear/cockpit/index.html"

[unit.ear.ros]
workspace = "."
packages = ["ear"]

[cockpit]
display_name = "Ear"
description = "Audio intake and VAD telemetry"
regimes = ["audio"]
