[package]
name = "pilot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cockpit"
path = "src/bin/cockpit.rs"

[dependencies]
anyhow = "1"
axum = { version = "0.7", features = ["ws"] }
futures = "0.3"
rclrs = "*"
std_msgs = { version = "*", path = "../install/share/std_msgs/rust" }
geometry_msgs = { version = "*", path = "../install/share/geometry_msgs/rust" }
nav_msgs = { version = "*", path = "../install/share/nav_msgs/rust" }
sensor_msgs = { version = "*", path = "../install/share/sensor_msgs/rust" }
create_msgs = { version = "*", path = "../install/share/create_msgs/rust" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "signal",
    "sync",
] }
tower = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
