name = "gps"
description = "u-blox GPS bring-up with gpsd integration"

[pilot]
display_name = "GPS"
description = "Satellite navigation telemetry"
regimes = ["navigation"]

[[pilot.topics]]
name = "/gps/fix"
type = "sensor_msgs/msg/NavSatFix"
access = "ro"
presentation = "map"
qos = { history = "keep_last", depth = 5, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/gps/velocity"
type = "geometry_msgs/msg/TwistStamped"
access = "ro"
presentation = "vector"
qos = { history = "keep_last", depth = 5, reliability = "reliable", durability = "volatile" }

[[actions]]
type = "link_packages"
packages = ["ublox_gps", "psyched_msgs"]

[[actions]]
type = "apt_install"
packages = ["gpsd", "gpsd-clients"]
update = true

[[actions]]
type = "run"
description = "Ensure user has dialout access"
script = "scripts/ensure_dialout.sh"
optional = true

[[actions]]
type = "run"
description = "Create udev rule for u-blox adapters"
script = "scripts/install_udev_rule.sh"
optional = true

[[actions]]
type = "run"
description = "Configure gpsd defaults"
script = "scripts/configure_gpsd.sh"
optional = true

[[actions]]
type = "run"
description = "Enable and start gpsd"
script = "scripts/enable_gpsd.sh"
optional = true

[[actions]]
type = "pip_install"
packages = ["gps3"]
import_check = ["gps3"]
break_system = true

[systemd]
description = "Psyched GPS Service"
after = ["network-online.target"]
wants = ["network-online.target"]
restart = "on-failure"
restart_sec = 5
launch_command = "${MODULE_DIR}/gps.launch.sh"
shutdown_command = "${MODULE_DIR}/gps.shutdown.sh"
