[unit.memory]
apt = []
pip = []
launch = "modules/memory/launch_unit.sh"
shutdown = "modules/memory/shutdown_unit.sh"
cockpit_control = "modules/memory/cockpit/index.html"

[unit.memory.ros]
workspace = "."
packages = ["memory", "memory_interfaces"]

[cockpit]
display_name = "Memory"
description = "Long-term semantic storage and recall services"
regimes = ["cognition"]
