[unit.memory]
apt = []
pip = []
launch = "modules/memory/launch_unit.sh"
shutdown = "modules/memory/shutdown_unit.sh"
pilot_control = "modules/memory/pilot/components/MemoryModulePanel.tsx"

[unit.memory.ros]
workspace = "."
packages = ["memory", "memory_interfaces"]
