[patch.crates-io.diagnostic_msgs]
path = "/home/pete/psyched/vendor_msgs/diagnostic_msgs"

[patch.crates-io.geometry_msgs]
path = "/home/pete/psyched/vendor_msgs/geometry_msgs"

[patch.crates-io.nav_msgs]
path = "/home/pete/psyched/vendor_msgs/nav_msgs"

[patch.crates-io.sensor_msgs]
path = "/home/pete/psyched/vendor_msgs/sensor_msgs"

[patch.crates-io.shape_msgs]
path = "/home/pete/psyched/vendor_msgs/shape_msgs"

[patch.crates-io.trajectory_msgs]
path = "/home/pete/psyched/vendor_msgs/trajectory_msgs"
