services:
  asr_fast:
    build:
      context: ..
      dockerfile: docker/asr-service.Dockerfile
    image: psyched-asr-service:local
    restart: unless-stopped
    environment:
      ASR_MODEL_PATH: "/models/ggml-tiny.en.bin"
      ASR_LANGUAGE: "en"
      ASR_QUALITY: "fast"
      ASR_THREADS: "4"
      NVIDIA_VISIBLE_DEVICES: "all"
    ports:
      - "8082:8082"
    volumes:
      - type: bind
        source: ../asr-service/models
        target: /models
        read_only: true
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-modeset:/dev/nvidia-modeset

  asr_medium:
    build:
      context: ..
      dockerfile: docker/asr-service.Dockerfile
    image: psyched-asr-service:local
    restart: unless-stopped
    environment:
      ASR_MODEL_PATH: "/models/ggml-small.en.bin"
      ASR_LANGUAGE: "en"
      ASR_QUALITY: "medium"
      ASR_THREADS: "6"
      NVIDIA_VISIBLE_DEVICES: "all"
    ports:
      - "8083:8082"
    volumes:
      - type: bind
        source: ../asr-service/models
        target: /models
        read_only: true
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-modeset:/dev/nvidia-modeset

  asr_long:
    build:
      context: ..
      dockerfile: docker/asr-service.Dockerfile
    image: psyched-asr-service:local
    restart: unless-stopped
    environment:
      ASR_MODEL_PATH: "/models/ggml-large-v3-q5_0.bin"
      ASR_LANGUAGE: "en"
      ASR_QUALITY: "long"
      NVIDIA_VISIBLE_DEVICES: "all"
    ports:
      - "8084:8082"
    volumes:
      - type: bind
        source: ../asr-service/models
        target: /models
        read_only: true
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-modeset:/dev/nvidia-modeset

  tts:
    build:
      context: ..
      dockerfile: docker/tts-websocket.Dockerfile
    image: psyched-tts-websocket:local
    restart: unless-stopped
    environment:
      TTS_MODEL: "tts_models/en/vctk/vits"
      TTS_USE_CUDA: "false"
      TTS_MODEL_DIR: "/models"
    ports:
      - "5002:5002"
    volumes:
      - type: bind
        source: ../tools/tts_websocket/models
        target: /models
        read_only: false

  llm:
    build:
      context: ..
      dockerfile: docker/forebrain-llm.Dockerfile
    image: psyched-forebrain-llm:local
    restart: unless-stopped
    environment:
      FOREBRAIN_LLM__MODEL__PATH: "/data/gpt-oss-20b-Q5_K_M.gguf"
      FOREBRAIN_LLM__WEBSOCKET__BIND_ADDR: "0.0.0.0:8080"
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - type: bind
        source: ../forebrain-llm/models
        target: /data
        read_only: false
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    ports:
      - "8080:8080"
