services:
  asr:
    build:
      context: ..
      dockerfile: docker/asr-fast.Dockerfile
    image: psyched-asr-fast:local
    restart: unless-stopped
    ports:
      - "8082:8082"

  tts:
    build:
      context: ..
      dockerfile: docker/tts-websocket.Dockerfile
    image: psyched-tts-websocket:local
    restart: unless-stopped
    environment:
      TTS_MODEL: "tts_models/en/vctk/vits"
    ports:
      - "5002:5002"

  llm:
    build:
      context: ..
      dockerfile: docker/forebrain-llm.Dockerfile
    image: psyched-forebrain-llm:local
    restart: unless-stopped
    environment:
      FOREBRAIN_LLM__MODEL__PATH: "/data/gpt-oss-20b.gguf"
      FOREBRAIN_LLM__WEBSOCKET__BIND_ADDR: "0.0.0.0:8080"
    volumes:
      - type: bind
        source: ../forebrain-llm/models
        target: /data
        read_only: false
    # Backwards-compatible GPU access for older docker-compose validators:
    # keep runtime for compatibility and expose common NVIDIA device nodes.
    # If you have the nvidia-container-toolkit and a modern Docker, it will still work.
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    ports:
      - "8080:8080"
