name = "eye"
description = "Kinect depth camera integration"

[pilot]
display_name = "Eye"
description = "RGB-D perception from the Kinect"
regimes = ["perception"]

[[pilot.topics]]
name = "/image_raw"
type = "sensor_msgs/msg/Image"
access = "ro"
presentation = "image"
qos = { history = "keep_last", depth = 3, reliability = "best_effort", durability = "volatile" }

[[pilot.topics]]
name = "/camera/depth/image_raw"
type = "sensor_msgs/msg/Image"
access = "ro"
presentation = "depth"
qos = { history = "keep_last", depth = 3, reliability = "best_effort", durability = "volatile" }

[[actions]]
type = "git_clone"
repo = "https://github.com/bribribriambriguy/kinect_ros2.git"
dest = "kinect_ros2"
branch = "frame_correction"

[[actions]]
type = "git_clone"
repo = "https://github.com/OpenKinect/libfreenect"
dest = "libfreenect"

[[actions]]
type = "run"
description = "Patch kinect_ros2 for cv_bridge"
script = "scripts/patch_kinect_cv_bridge.sh"
optional = true

[[actions]]
type = "run"
description = "Replace legacy cv_bridge headers"
script = "scripts/replace_cv_bridge_headers.sh"
optional = true

[[actions]]
type = "run"
description = "Install Kinect vision dependencies"
script = "scripts/install_kinect_deps.sh"
optional = true

[[actions]]
type = "run"
description = "Build and install libfreenect"
script = "scripts/build_libfreenect.sh"
optional = true

[systemd]
description = "Psyched Eye"
after = ["network-online.target"]
wants = ["network-online.target"]
restart = "on-failure"
restart_sec = 6
launch_command = "${MODULE_DIR}/eye.launch.sh"
shutdown_command = "${MODULE_DIR}/eye.shutdown.sh"
