system_prompt: "You are a helpful assistant. Your reply should only be about one sentence. You will have a chance to continue the conversation further. Allow your interlocutor a chance to speak."
conversation_topic: /conversation
voice_topic: /voice
ollama_model: tinyllama
ollama_host: "http://localhost:11434"
max_history: 20
