# Module configuration overrides for voice.
# Provide [launch.arguments] entries keyed by launch argument name.

[launch.arguments]

ping_enabled = true
# Use the forebrain host for websocket TTS (resolves on local network)
tts_ws_url = "ws://forebrain.local:5002/tts"
