[unit.chat]
apt = []
pip = ["ollama"]
patches = [
    "modules/chat/scripts/install_ollama.sh",
    "modules/chat/scripts/enable_ollama_service.sh",
    "modules/chat/scripts/ensure_ollama_model.sh",
]
launch = "modules/chat/launch_unit.sh"
shutdown = "modules/chat/shutdown_unit.sh"

[unit.chat.ros]
workspace = "."
packages = ["chat", "psyched_msgs"]
