[unit.chat]
apt = []
launch = "modules/chat/launch_unit.sh"
shutdown = "modules/chat/shutdown_unit.sh"
cockpit_control = "modules/chat/cockpit/index.html"

[unit.chat.ros]
workspace = "."
packages = ["chat", "psyched_msgs"]

[cockpit]
display_name = "Chat"
description = "Conversational agent powered by Ollama"
regimes = ["conversation"]
