[unit.pilot]
# Pilot frontend dependencies handled via Deno; no system packages required yet
apt = []
pip = []

# Pilot module does not require patch scripts
patches = []

# Service control
launch = "modules/pilot/launch_unit.sh"
shutdown = "modules/pilot/shutdown_unit.sh"
pilot_control = "modules/pilot/pilot/components/PilotOverview.tsx"

[[unit.foot.git]]
# TODO: this is a global dependency, move to `psh setup`
url = "https://github.com/ros2-rust/cargo-ament-build.git"

[[unit.foot.git]]
# TODO: this is a global dependency, move to `psh setup`
url = "https://github.com/colcon/colcon-ros-cargo.git"
