[unit.pilot]
apt = [
    "ros-${ROS_DISTRO}-example-interfaces",
    "ros-${ROS_DISTRO}-test-msgs",
    "ros-${ROS_DISTRO}-web-video-server",
    "ros-${ROS_DISTRO}-sensor-msgs",
    "python3-typing-extensions",
]
pip = [
    "websockets>=10,<13",
    "typing_extensions>=4.8,<5",
]

# Apply overlays needed for ROS workspace builds.
patches = [
    "modules/pilot/scripts/ensure_cv_bridge_overlay.sh",
]

# Service control
launch = "modules/pilot/launch_unit.sh"
shutdown = "modules/pilot/shutdown_unit.sh"
pilot_control = "modules/pilot/components/PilotOverview.tsx"
