[unit.pilot]
apt = [
    "python3-aiohttp",
    "python3-yaml",
    "ros-${ROS_DISTRO}-image-transport-plugins",
    "ros-${ROS_DISTRO}-rosbridge-suite",
    "ros-${ROS_DISTRO}-tf2-web-republisher",
    "ros-${ROS_DISTRO}-web-video-server",
]
pip = [
    "tomli-w>=1.0",
]
launch = "modules/pilot/launch_unit.sh"
shutdown = "modules/pilot/shutdown_unit.sh"
pilot_control = "modules/pilot/packages/pilot/pilot/frontend/index.html"

[unit.pilot.ros]
workspace = "."
packages = ["pilot"]

[pilot]
display_name = "Pilot"
description = "Teleoperation dashboard and ROS 2 bridge"
mod_commands = ["setup", "up", "down", "teardown"]
regimes = ["system"]
