[pilot]
display_name = "Pilot"
description = "Teleoperation dashboard and ROS 2 bridge"
mod_commands = ["setup", "build", "launch", "restart", "shutdown"]
system_commands = ["start", "stop", "restart", "status"]
regimes = ["system"]

[[pilot.topics]]
name = "/cmd_vel"
type = "geometry_msgs/msg/Twist"
presentation = "joystick"
access = "rw"
qos = { history = "keep_last", depth = 5, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/imu"
type = "sensor_msgs/msg/Imu"
presentation = "imu"
qos = { history = "keep_last", depth = 20, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/host/health"
type = "psyched_msgs/msg/HostHealth"
access = "ro"
presentation = "status"
qos = { history = "keep_last", depth = 5, reliability = "reliable", durability = "volatile" }

[[actions]]
type = "link_packages"
packages = ["pilot"]

[[actions]]
type = "run"
description = "Install ROS Python shims via apt"
script = "scripts/install_ros_python_deps.sh"

[[actions]]
type = "pip_install"
packages = ["fastapi", "uvicorn[standard]", "pydantic", "psutil", "pyyaml"]
import_check = ["fastapi"]
break_system = true

[systemd]
description = "Psyched Pilot UI"
after = ["network-online.target"]
wants = ["network-online.target"]
restart = "on-failure"
restart_sec = 4
launch_command = "${MODULE_DIR}/pilot.launch.sh"
shutdown_command = "${MODULE_DIR}/pilot.shutdown.sh"
