[unit.pilot]
apt = [
    "ros-${ROS_DISTRO}-example-interfaces",
    "ros-${ROS_DISTRO}-test-msgs",
    "ros-${ROS_DISTRO}-rosbridge-server",
    "ros-${ROS_DISTRO}-web-video-server",
    "ros-${ROS_DISTRO}-sensor-msgs",
]
pip = []

# Pilot module does not require patch scripts
patches = []

# Service control
launch = "modules/pilot/launch_unit.sh"
shutdown = "modules/pilot/shutdown_unit.sh"
pilot_control = "modules/pilot/pilot/components/PilotOverview.tsx"
