[unit.voice]
apt = ["espeak", "alsa-utils"]
pip = ["websockets>=11.0.0"]
launch = "modules/voice/launch_unit.sh"
shutdown = "modules/voice/shutdown_unit.sh"
cockpit_control = "modules/voice/cockpit/index.html"

[unit.voice.ros]
workspace = "."
pip = ["websockets>=12,<13"]
display_name = "Voice"
description = "Text-to-speech synthesis"
regimes = ["audio"]
