name = "voice"
description = "Text-to-speech pipeline"

[pilot]
display_name = "Voice"
description = "Text-to-speech synthesis"

[[pilot.topics]]
name = "/voice"
type = "std_msgs/msg/String"
access = "rw"
presentation = "text"
qos = { history = "keep_last", depth = 10, reliability = "reliable", durability = "volatile" }

[[pilot.topics]]
name = "/voice/interrupt"
type = "std_msgs/msg/Empty"
access = "wo"
presentation = "button"
qos = { history = "keep_last", depth = 1, reliability = "reliable", durability = "volatile" }

[[actions]]
type = "link_packages"
packages = ["voice", "psyched_msgs"]

[[actions]]
type = "apt_install"

[[actions]]
type = "link_packages"
packages = [
    "espeak-ng",
    "mbrola",
    "mbrola-en1",
    "ffmpeg",
    "fortune-mod",
    "fortunes",
    "fortunes-min",
]
update = true

[[actions]]
type = "pip_install"
packages = ["pyttsx3"]
import_check = ["pyttsx3"]
break_system = true

[systemd]
description = "Psyched Voice"
after = ["network.target"]
restart = "on-failure"
restart_sec = 4
launch_command = "${MODULE_DIR}/voice.launch.sh"
shutdown_command = "${MODULE_DIR}/voice.shutdown.sh"
