[unit.voice]
apt = [
    "espeak",
]
pip = []
launch = "modules/voice/launch_unit.sh"
shutdown = "modules/voice/shutdown_unit.sh"
pilot_control = "modules/voice/pilot/index.html"

[unit.voice.ros]
workspace = "."
packages = ["voice"]

[pilot]
display_name = "Voice"
description = "Text-to-speech synthesis"
regimes = ["audio"]
