name = "voice"
description = "Text-to-speech pipeline"

[[actions]]
type = "link_packages"
packages = ["voice", "psyched_msgs"]

[[actions]]
type = "apt_install"
packages = ["espeak-ng", "mbrola", "mbrola-en1", "ffmpeg", "fortune-mod", "fortunes", "fortunes-min"]
update = true

[[actions]]
type = "pip_install"
packages = ["pyttsx3"]
import_check = ["pyttsx3"]
break_system = true

[systemd]
description = "Psyched Voice"
after = ["network.target"]
launch = "modules/voice/launch.sh"
shutdown = "modules/voice/shutdown.sh"
restart = "on-failure"
restart_sec = 4
