[unit.hypothalamus]
apt = [
    "python3-smbus2",
]
pip = [
    "adafruit-circuitpython-dht",
    "adafruit-blinka",
]
launch = "modules/hypothalamus/launch_unit.sh"
shutdown = "modules/hypothalamus/shutdown_unit.sh"
cockpit_control = "modules/hypothalamus/cockpit/index.html"

[[unit.hypothalamus.git]]
url = "https://github.com/adafruit/Adafruit_CircuitPython_DHT.git"
path = "external/Adafruit_CircuitPython_DHT"

[unit.hypothalamus.ros]
workspace = "."
packages = ["hypothalamus"]
