name: E2E Scenarios

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Run e2e scenarios
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Prime Deno cache
        run: deno cache psh/e2e/mod.ts

      - name: Prepare report directory
        run: mkdir -p reports

      - name: Execute scenarios
        env:
          DENO_TLS_CA_STORE: system
        run: deno task e2e

      - name: Upload junit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-junit-report
          path: reports/e2e.xml
          if-no-files-found: warn
